YogiyoCloneTeamProject/YogiYoCloneIOS

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Info.plist
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/MainTabVC/MainTabVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/AccountVC/AccountVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HistoryVC/HistoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailMenuVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/MenuListVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/HomeVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/StoreListVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/LikeVC/LikeVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/SearchVC/SearchVC.swift

feat: 협업전 기본 세팅

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Info.plist
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/ColorPiker.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailMenuVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/FontModel.swift

확인부탁드려요~ 내 폴더에 넣어놔서 모델로 이동부탁!!...

모델추가(Color,Font)

---

.gitattributes

feat: gitattributes 추가

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

StoreList TableView Setting

---

YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

Section Header & Autolayout edit

Section Header & Autolayout edit

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

Tableview Cell AutoLayout Edit & Star/ Review 추가

Tableview Cell AutoLayout Edit & Star/ Review 추가

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/Custom/RestaurantNewCustomCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/Custom/RestaurantPlusCustomCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/HomeVC.swift

Feat: Creat ninthCollection

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Info.plist
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/AccountVC/Dong/TableViewCell/LogVCCell/SocialLogCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/AccountVC/Dong/ViewController/LogVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/AccountVC/Dong/ViewController/LoggedAccountVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/AccountVC/Dong/ViewController/ProfileEditVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/Custom/StretchHeaderLayout.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/Extension/ObserveKey.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/View/BottomView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/View/StatusView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/ViewController/MenuListVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/YogiYoCloneIOS.entitlements

feat: Bottom Order Button 추가

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Network.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

PageViewController 생성

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Model/StoreListModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Service/StoreinfoFetch.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/YogiyoPlusStoreListVC.swift

yogiyoplusVC 추가

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Model/DataModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Service/StoreinfoFetch.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/CategoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

StoreVC : API Data Parcing

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/Custom/BottomView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/Extension/CollectionViewDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/HomeVC.swift

Feat: Extension UICollectionViewDelegate

Feat: Extension UICollectionViewDelegate

---

YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Pyo/Extension/CollectionViewDelegate.swift

Feat: Extension UICollectionViewDelegate edit

Feat: Extension UICollectionViewDelegate edit

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Model/DataModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Dong/ViewController/MenuListVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/View/CustomTopCategoryView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/CategoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

StoreVC : MenuList 화면연결

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/Model/DataModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Service/StoreinfoFetch.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/View/StoreFilterbigView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/View/StoreListFilterView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/CategoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

Data Model & StoreVC : category Data Edit

Data Model & StoreVC : category Data Edit

---

YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/CategoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/ViewController/StoreListVC.swift

StoreVC : protocol 추가

---

YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/View/StoreFilterbigView.swift

StoreVC : Navigation Title Edit

StoreVC : Navigation Title Edit

---

YogiYoCloneIOS/YogiYoCloneIOS/Model/DataModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Service/StoreinfoFetch.swift

Data Model : Edit  review-count

Data Model : Edit  review-count

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HistoryVC/Siroo/ViewController/HistoryTableVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Siroo/Service/StoreinfoFetch.swift

StoreVC : Order filtering parameter Edit

StoreVC : Order filtering parameter Edit

---

README.md

fix: README 수정

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailVC/DetailMenuVC.swift

feat: fech data() - id

---

YogiYoCloneIOS/YogiYoCloneIOS/Model/DataModel.swift

DataModel: OrderList Model Edit

DataModel: OrderList Model Edit

---

YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailVC/DetailMenuVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/OrderVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/SearchVC/Byun/SearchVC.swift

OrderVC - alert
SearchVC - url encodedString

feat : OrderVC - alert, SearchVC - url encodedString

---

README.md
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailVC/DetailMenuVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailVC/ShareVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/DetailVC/View/ShareView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/OderModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/OrderVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section0/LoginCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section1/CustomOrderCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section1/InformationCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section2/PaywithCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section3/MembershipCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section4/OrderlistCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section4/miniListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/HomeVC/Byun/OrderVC/Section5/paymentCell.swift

feat : DetailMenuVC - tableview layout, 
docs : readme수정
요청하는 소감
[로그인 - 주기능 - 부가기능]의 하나의 전체적인 서비스 사이클을 완성하는 앱을 개발함으로서, 앱의 전체적인 이해와 개발환경에 대한 개념(서버관리,에러처리,데이터관리 등)을 높일 수 있었다. UI , Model(Data), API 를 숙련할 수 있었던 좋은 프로젝트였다. 
iOS동료들과 백엔드와의 장기간 팀프로젝트로 협업에 대한 경험(커뮤니케이션, 발표 준비등)이 특히 의미있었다.

feat : DetailMenuVC - tableview layout, docs : readme수정

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Info.plist
YogiYoCloneIOS/YogiYoCloneIOS/Model/DataModel.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/SectionView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/StoreButtonView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/deliveryImage.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/ViewController/HistoryDetailVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/ViewController/HistoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/ViewController/CategoryVC/CategoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/ViewController/StoreListCell.swift

StoreVC Cell : Properties Edit

StoreVC Cell : Properties Edit

---

YogiYoCloneIOS/YogiYoCloneIOS.xcodeproj/project.pbxproj
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/Custom/MapVC/NearestListCustomCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/Extension/MapVC/MapTableViewData.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/Extension/MapVC/MapTableViewDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/ViewController/MapVC/MapVC.swift

Feat: resolve MapVC tableView bug

Feat: resolve MapVC tableView bug

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/Info.plist
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/Extension/MapVC/GoogleMapDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/Extension/MapVC/MapTableViewDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/View/MapVC/GoogleBottomView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/ViewController/HomeVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/ViewController/MapVC/GoogleMapVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Pyo/ViewController/MapVC/MapVC.swift

Feat: complete GoogleMapVC

---

.gitattributes

Feat: edit .gitattributes

---

YogiYoCloneIOS/YogiYoCloneIOS/Base.lproj/LaunchScreen.storyboard

Feat: edit readme.md

---

YogiYoCloneIOS/YogiYoCloneIOS/AppDelegate.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/Service/HistoryInfoFetch.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/CloseButton.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/ReOrderButton.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/StackBig.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryDetail/WrapView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/HistoryEmptyView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/View/MyListBannerView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/ViewController/HistoryDetailVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/HistoryVC/ViewController/HistoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/View/CustomTopCategoryView.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/ViewController/CategoryVC/CategoryVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/ViewController/StoreListCell.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/ViewController/StoreListVC.swift
YogiYoCloneIOS/YogiYoCloneIOS/ViewController/ViewControllers/Siroo/ViewController/YogiyoPlusStoreListVC.swift

AppDelegate Edit
